<?php
return array(
  'backgroundimageheadlinebox' => '/BackgroundImageHeadline/Box.php',
  'backgroundimageheadlineboxbase' => '/BackgroundImageHeadline/Box/Base.php',
  'papayabasepagesconnector' => '/PagesConnector.php',
  'actionbox_background_image' => '/actbox_background_image.php',
  'actionbox_categteaser' => '/actbox_categteaser.php',
  'actionbox_categteaserthumb' => '/actbox_categteaserthumb.php',
  'actionbox_html' => '/actbox_html.php',
  'actionbox_pagelink' => '/actbox_pagelink.php',
  'actionbox_pagelink_extended' => '/actbox_pagelink_extended.php',
  'actionbox_prevnext' => '/actbox_prevnext.php',
  'actionbox_richtext' => '/actbox_richtext.php',
  'actionbox_richtextfilter' => '/actbox_richtextfilter.php',
  'actionbox_sitemap' => '/actbox_sitemap.php',
  'actionbox_tagteaser' => '/actbox_tagteaser.php',
  'actionbox_tagteaserthumb' => '/actbox_tagteaserthumb.php',
  'content_boxgrid' => '/content_boxgrid.php',
  'content_casestudy' => '/content_casestudy.php',
  'content_categimg' => '/content_categimg.php',
  'content_errorpage' => '/content_errorpage.php',
  'content_imgtopic' => '/content_imgtopic.php',
  'content_sitemap' => '/content_sitemap.php',
  'content_softlink' => '/content_softlink.php',
  'content_tagcateg' => '/content_tagcateg.php',
  'content_teaserlink' => '/content_teaserlink.php',
  'content_url' => '/content_url.php',
  'content_xhtml' => '/content_xhtml.php',
  'datafilter_tag' => '/datafilter_tag.php',
  'filter_xslt' => '/filter_xslt.php'
);